PAYPAL_CLIENT_ID="AWpLyOq61JTy_0gUzMFiKDoaWJPeCdahdV3O_oFtIGhTHR7xUyZYWZVKm_jo7GW2lctDNYFzmeSxJrMr"
PAYPAL_CLIENT_SECRET="EN9x2D8hLzSMLy9T06jr4EnDuZxjJvIoJffuxp4ZN4B_UCmE-k7CuHXSDxiVVmw_ORFiiPqwkdvd3eA7"
